Clean out all doc building warnings/errors.
OpenMDAO/OpenMDAO_Book pull request #148
Opened 2021-05-11 21:24 UTC by Kenneth-T-Moore

1. Modified doc build so that all warnings are raised as errors. This way, the build will fail if a test fails, and we don't need to run the tests.
2. Added the necessary sphinx plugins to process the numpydocs docstrings correctly.
3. Fixed a wide arrange of actual problems in the docs; these were found in the build warnings.
4. Pointed jupyter-notebook to the latest repo to get around some bugs that were fixed recently.
5. Converted most remaining markdown files to notebooks so that the orphan metadata could be added.
6. Removed unit test that runs the tests in the notebook cells, because it is now redundant.  
7. Added items to the toc to give it consistent depth.

2021-05-14 15:00 UTC, DKilkenny commented
- list_variable's `.. automethod::` not formatted

2021-05-14 15:00 UTC, DKilkenny requested changes

2021-05-14 17:50 UTC, Kenneth-T-Moore commented on openmdao_book/features/debugging/newton_solver_not_converging.ipynb
> +    "  - Use [list_outputs()](listing_variables) to look at the state variable values and see if anything has taken on a bad value (e.g. 0 or 1e500) that causes the derivative to be ill-defined.\n",
Fixed

2021-05-14 17:50 UTC, Kenneth-T-Moore commented on openmdao_book/features/experimental/approx_coloring.ipynb
>    {
Fixed

2021-05-18 19:00 UTC, DKilkenny approved these changes

2021-05-18 19:04 UTC, merged